version: '3.8'

services:
  backend:
    image: rbasstos/kodominio-api
    ports:
      - "8080:8080"
    networks:
      - web
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kodominio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Celo1337,

  frontend:
    image: rbasstos/kodominio-front
    ports:
      - "80:80"
    networks:
      - web

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: kodominio
      MYSQL_ROOT_PASSWORD: Celo1337,
    ports:
      - "3306:3306"
    networks:
      - web

networks:
  web:
    driver: overlay